### ISSUE TITLE
Input Parameters Error

### ISSUE THREAD

**Issue by Gitagat** [andrei-m-code/net-core-html-to-image#3]
I get an invalid parameter error when trying to run the Convert HTML string to image bytes example. I am using the exact code from the example just to see if it works.

It throws on this line: 
`var bytes = converter.FromHtmlString(html);`

The error says:
>   System.Exception
>   HResult=0x80131500
>   Message=Something went wrong. Please check input parameters
>   Source=CoreHtmlToImage
>   StackTrace:
>    at CoreHtmlToImage.HtmlConverter.FromUrl(String url, Int32 width, ImageFormat format, Int32 quality)

I am using Windows, Visual Studio Community, .Net Core 2.1

**Comment by 00raq00** [comment]
I can see this exception for some html files  I found today that included wkhtmltoimage 0.12.5 has problem with some html files. Newer version 0.12.6 works fine. After manually replacing exe inside dll, this reported error stopped throwing and the jpg file is created.

Could you update exe (Resource) inside lib?
