### ISSUE TITLE
This URL doesn't convert to image

### ISSUE THREAD

**Issue by rgelb** [andrei-m-code/net-core-html-to-image#4]
I have the following code with the public URL:

    var converter = new HtmlConverter();
    string url = "https://www.xome.com/QWidget/addressImage.aspx?zip=94066&widget=price-history&propertyAddress=115%20Madison%20Ave&token=:TOKEN:=AQAAAAUAAABVMDAxNgwAAADwVafbtt1vhs9OkIcQAAAAMtEZwtIxlqlRK3Px8691zTsAAAD0gpwM-WCVCtDnuy1XjDIPwfHKqfL6-mbPSnhSdMZqvRbmpeQE2h7rF3CwsVjV8bSQBd8p9uRbgWpfQw==";
    var bytes = converter.FromUrl(url);
    File.WriteAllBytes("image.jpg", bytes);

It generates a 1024x10 jpg with a white background.

**Comment by danielfdutra** [comment]
This site doesn't have any renderable HTML. If you try to send a `GET` request to it, it only returns a HTML with empty `<div>`s and scripts inside the `<body>`.  
You should try to access this url some other way, load all html and scripts and then send the HTML you loaded to `FromUrl`.
