### ISSUE TITLE
Adding Height parameter

### ISSUE THREAD

**Issue by Augmensis** [andrei-m-code/net-core-html-to-image#6]
I've created an overload in my cloned copy of the repo that allows control over the image Height with a default of 1024. For backwards compatibility the height arguments for FromHtmlString() and FromUrl() is at the end of the method so existing code is not affected if anyone upgrades their package.

May I contribute my changes for review please?

**Comment by andrei-m-code** [comment]
@Augmensis go ahead. Thank you!
