### ISSUE TITLE
Getting Error while passing Html to function

### ISSUE THREAD

**Issue by AjayRawat232** [andrei-m-code/net-core-html-to-image#8]
Hi,

Thanks for the tool.
Can you please help me i am stuck in between of my process and getting error as follow.
I am working in ASP.NET Core Project.

using the same code block as follow
Code :-
var converter = new HtmlConverter();
var html = "<div><strong>Hello</strong> World!</div>";
var bytes = converter.FromHtmlString(html);

Exception :-
Please check input parameters
   at CoreHtmlToImage.HtmlConverter.FromUrl(String url, Int32 width, ImageFormat format, Int32 quality)
   at CoreHtmlToImage.HtmlConverter.FromHtmlString(String html, Int32 width, ImageFormat format, Int32 quality)

Fast reply will help me out from the situation.

Thanks

**Comment by andrei-m-code** [comment]
@AjayRawat232 have you tried with string `<p><strong>Hello</strong>, World<p>`?
